service: anikunchan-token

provider:
  name: aws
  runtime: nodejs6.10

functions:
  getToken:
    handler: handler.getToken
    environment:
      ANILIST_CLIENT_ID: ${file(env.yml):ANILIST_CLIENT_ID}
      ANILIST_CLIENT_SECRET: ${file(env.yml):ANILIST_CLIENT_SECRET}
    events:
      - http:
          path: token
          method: get
          cors: true